<form action="<?php echo Mage::getUrl('wbxtest/index/save') ?>" method="POST" class="testimonialsform">
    <table class="table">
        <tr>
            <td>Title</td>
            <td><input type="text" name="name" id="name" /></td>
        </tr>
        <tr>
            <td>Text</td>
            <td><textarea name="description" id="description" ></textarea></td>
        </tr>
        <tr>
            <td>Rating</td>
            <td>
                <select id="value" name="value">
                    <?php foreach (range(1, 5) as $rat) { ?>
                        <option value="<?php echo $rat ?>"><?php echo $rat ?></option>
                    <?php } ?>
                </select>
            </td>
        </tr>
        <tr>
            <td></td>
            <td><input type="submit" /></td>
        </tr>
    </table>
</form>

